<!DOCTYPE html>
<html>

<head>
<title> Accion-usuario</title>
<link rel="stylesheet" href="/css/main.css">
</head>

  <body>
  <div class="formulario">
   <h1>Accion-usuario</h1>
    <form action="/registro" method="post">

    <div class="element-container container-tipo">
       <label for="tipo" class="label label-tipo">Tipo:</label>
       <div class="container-tipo">
       
       <select name="tipo" id="tipo" class="center select-tipo">
       <option value="like">like</option>
       <option value="view">view</option>
       <option value="comment">comment</option>
       <option value="retweet">retweet</option>
       </select>
    </div>
    <div class="element-container container-tipo">
       <label for="tipo" class="label label-tipo">Tipo:</label>
       <div class="container-tipo">
       
       <select name="tipo" id="tipo" class="center select-tipo">
       <option value="like">like</option>
       <option value="view">view</option>
       <option value="comment">comment</option>
       <option value="retweet">retweet</option>
       </select>
    </div>
    </form>
  </div>
  </body>


</html>