<!DOCTYPE html>
<html>

<head>
<title> Accion</title>
<link rel="stylesheet" href="/css/main.css">
</head>

  <body>
   
    <div class="formulario accion">
   <h1>Accion</h1>
    <form action="/registro" method="post">
    <div class="element-container container-accion">
      <label for="accion">Accion:</label>
      <input type="text" name="accion" class="text name">
    </div>
    </form>
  </div>
  </body>


</html>