<!DOCTYPE html>
<html>

<head>
<title> Pais</title>
<link rel="stylesheet" href="/css/main.css">
</head>

  <body>
  <div class="formulario pais">
   <h1>Pais</h1>
    <form action="/registro" method="post">
    <div class="element-container container-pais">
      <label for="pais">Pais:</label>
      <input type="text" name="pais" class="text name">
    </div>
    </form>
    </div>
  </body>


</html>